name: Fetch Terraform Output
description: Restore Terraform output from cache or pull from HCP

inputs:
  workspace:
    required: true
    type: string
  environment:
    required: true
    type: string
  VAR_PATH_TEMP:
    required: true
    type: string
  TERRAFORM_API_TOKEN:
    required: true

runs:
  using: "composite"
  steps:
    # Set environment path
    - name: Set environment path
      shell: bash
      run: |
        mkdir -p ${{ inputs.VAR_PATH_TEMP }}
        echo "VAR_PATH_TEMP=${{ inputs.VAR_PATH_TEMP }}" >> "$GITHUB_ENV"

    # Restore Terraform Cache
    - name: Restore Terraform Cache
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ env.VAR_PATH_TEMP }}/tf_output.json
        key: terraform-output-${{ inputs.workspace }}

    # Check for Restored Terraform Output
    - name: Check for Restored Terraform Output
      id: check-cache
      shell: bash
      run: |
        if [ -f "${VAR_PATH_TEMP}/tf_output.json" ]; then
          echo "found=true" >> "$GITHUB_OUTPUT"
        else
          echo "found=false" >> "$GITHUB_OUTPUT"
        fi

    # Setup Terraform CLI
    - name: Setup Terraform CLI
      if: steps.check-cache.outputs.found == 'false'
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    # Download Terraform Output from HCP
    - name: Download Terraform Output from HCP
      if: steps.check-cache.outputs.found == 'false'
      shell: bash
      env:
        TF_TOKEN_app_terraform_io: ${{ inputs.TERRAFORM_API_TOKEN }}
      run: |
        terraform login -no-color || true
        terraform pull -workspace="${{ inputs.workspace }}" > "${VAR_PATH_TEMP}/tfstate.tfstate"
        terraform show -json "${VAR_PATH_TEMP}/tfstate.tfstate" | jq '.values.outputs' > "${VAR_PATH_TEMP}/tf_output.json"

    # Debug output
    - name: View Debug Output
      shell: bash
      run: |
        jq '.' ./.temp/tf_output.json | head -n 20
