apiVersion: platform.huybrechts.xyz/v1.0
kind: resourceType
metadata:
  name: vm-infra
  description: Infrastructure Virtual Machine
spec:
  type: virtualmachine
  properties:
    cpuType: A
    cpuCores: 1
    ramMb: 4096
    unitCost: 11.00
  disks:
    - size: 20
      label: "${resourceId}-os"
    - size: 40
      label: "${resourceId}-data"
  mounts:
    - type: config
      disk: 2
    - type: docs
      disk: 2
    - type: data
      disk: 2
    - type: logs
      disk: 2
    - type: serve
      disk: 2
  mountpoint: "/mnt/data${disk}/app"
