apiVersion: platform.huybrechts.xyz/v1.0
kind: resourceType
metadata:
  name: vm-worker
  description: Worker Virtual Machine
spec:
  type: virtualmachine
  properties:
    cpuType: A
    cpuCores: 1
    ramMb: 2048
    unitCost: 6.00
  disks:
    - size: 20
      label: "${resourceId}-os"
  mounts:
    - type: config
      disk: 1
    - type: docs
      disk: 1
    - type: data
      disk: 1
    - type: logs
      disk: 1
    - type: serve
      disk: 1
  mountpoint: "/mnt/data${disk}/app"
