apiVersion: platform.huybrechts.xyz/v1.0
kind: Workspace
metadata:
  name: platform
  labels:
    workspace: platform
spec:
  description: Platform Workspace on Kamatera
  version: 1.0.0
  providers:
    - name: kamatera
      type: CloudProvider
      description: Kamatera Cloud Provider
      properties:
        region: eu-fr

---
apiVersion: platform.example.com/v1alpha1
kind: Resource
metadata:
  name: manager-1
spec:
  resourceType: vm-manager
  labels: {}
  properties:
    disks:
      - label: manager-1-os

---
apiVersion: platform.example.com/v1alpha1
kind: Resource
metadata:
  name: infra-1
spec:
  resourceType: vm-infra
  labels: {}
  properties:
    disks:
      - label: infra-1-os
      - label: infra-1-data

---
apiVersion: platform.example.com/v1alpha1
kind: Resource
metadata:
  name: infra-2
spec:
  resourceType: vm-infra
  labels: {}
  properties:
    disks:
      - label: infra-2-os
      - label: infra-2-data

---
apiVersion: platform.example.com/v1alpha1
kind: Resource
metadata:
  name: worker-1
spec:
  resourceType: vm-worker
  labels: {}
  properties:
    disks:
      - label: worker-1-os

---
apiVersion: platform.example.com/v1alpha1
kind: Resource
metadata:
  name: worker-2
spec:
  resourceType: vm-worker
  labels: {}
  properties:
    disks:
      - label: worker-2-os

---
apiVersion: platform.example.com/v1alpha1
kind: Variables
metadata:
  name: platform-vars
spec:
  variables:
    - key: WORKSPACE
      value: platform
    - key: DATACENTER
      value: kamatera-eu-fr
    - key: DOCKER_WORKER
      value: worker
    - key: DOMAIN_DEV
      value: huybrechts.dev
    - key: DOMAIN_XYZ
      value: huybrechts.xyz
    - key: DOMAIN_LIZARD
      value: theorderoftheblacklizard.be
    - key: DOMAIN_RPG
      value: alderwyn.xyz
    - key: PLATFORM_EMAIL
      value: webmaster@huybrechts.xyz
    - key: PLATFORM_SQL_NAME
      value: platform-db

---
apiVersion: platform.example.com/v1alpha1
kind: Secrets
metadata:
  name: platform-secrets
spec:
  secrets:
    - key: PLATFORM_USERNAME
      source: bitwarden
      id: 09171644-23c8-4b7f-9015-a4572
    - key: PLATFORM_PASSWORD
      source: bitwarden
      id: ffa5e6f9-de6a-47fa-887e-b2e5015ae1a4

---
apiVersion: platform.example.com/v1alpha1
kind: Module
metadata:
  name: traefik
spec:
  repository: huybrechtsxyz/xyz-traefik
  reference: dev-traefik
  config: deploy/service.json
  deploy: deploy
  namespace: app
  environment: infra
  priority: 1
  state: enabled


workspace:
  id: platform
  name: Platform Workspace on Kamatera
  version: 1.0.0
  description: Workspace deployment configuration for the shared Kamatera Platform.
  organization: XYZ Platform

  providers:
    - name: kamatera
      type: cloudprovider
      description: Kamatera Cloud Provider
      properties:
        region: eu-fr
  
  templates:
    - name: vm-manager
      type: virtualmachine
      description: Virtual Machine
      properties:
        cpu_type: A
        cpu_cores: 1
        ram_mb: 1024
        unit_cost: 5.00
        disks:
          - size: 20
            label: ${id}-os
        mountpoint: /mnt/data${disk}/app
        mounts:
          - type: config
            disk: 1
          - type: docs
            disk: 1
          - type: data
            disk: 1
          - type: logs
            disk: 1
          - type: serve
            disk: 1
    - name: vm-infra
      type: virtualmachine
      description: Infrastructure Virtual Machine
      properties:
        cpu_type: A
        cpu_cores: 1
        ram_mb: 4096
        unit_cost: 11.00
        disks:
          - size: 20
            label: ${id}-os
          - size: 40
            label: ${id}-data
        mountpoint: /mnt/data${disk}/app
        mounts:
          - type: config
            disk: 2
          - type: docs
            disk: 2
          - type: data
            disk: 2
          - type: logs
            disk: 2
          - type: serve
            disk: 2
    - name: vm-worker
      type: virtualmachine
      description: Worker Virtual Machine
      properties:
        cpu_type: A
        cpu_cores: 1
        ram_mb: 2048
        unit_cost: 6.00
        mountpoint: /mnt/data${disk}/app
        disks:
          - size: 20
            label: os
        mounts:
          - type: config
            disk: 1
          - type: docs
            disk: 1
          - type: data
            disk: 1
          - type: logs
            disk: 1
          - type: serve
            disk: 1