apiVersion: platform.huybrechts.xyz/v1.0
kind: workspace
meta:
  name: platform
  description: Platform Workspace on Kamatera
  version: 1.0.0
spec:
  variables:
    - key: WORKSPACE
      value: platform
    - key: DATACENTER
      value: kamatera-eu-fr
    - key: DOCKER_WORKER
      value: worker
    - key: DOMAIN_DEV
      value: huybrechts.dev
    - key: DOMAIN_XYZ
      value: huybrechts.xyz 
    - key: DOMAIN_LIZARD
      value: theorderoftheblacklizard.be
    - key: DOMAIN_RPG
      value: alderwyn.xyz
    - key: PLATFORM_EMAIL
      value: webmaster@huybrechts.xyz
    - key: PLATFORM_DATABASE
      value: platform-db

  secrets:
    # Credentials for Terraform
    - key: TERRAFORM_API_TOKEN
      source: bitwarden
      value: d47e736b-2db8-47d5-b46b-b2c8016ece73
    # Credentials for Kamatera
    - key: KAMATERA_API_KEY
      source: bitwarden
      value: 357068b9-9f5f-4f79-940c-b2c8016cb88f
    - key: KAMATERA_API_SECRET
      source: bitwarden
      value: 6c9295a8-9fa4-4d38-8929-b2c8016d9b43
    - key: KAMATERA PUBLIC_KEY
      source: bitwarden
      value: 6cc5b975-56a9-4d7a-80c7-b2c90151cce0
    - key: KAMATERA_ROOT_PASSWORD
      source: bitwarden
      value: 5083ae32-429d-428b-b7df-b2c901441bbb
    # Platform credentials    
    - key: PLATFORM_USERNAME
      source: bitwarden
      value: 09171644-23c8-4b7f-9015-b2e5015a4572
    - key: PLATFORM_PASSWORD
      source: bitwarden
      value: ffa5e6f9-de6a-47fa-887e-b2e5015ae1a4

  providers:
    - name: kamatera
      tags: [ cloudprovider ]
      properties:
        country: Germany
        region: Frankfurt

  templates:
    - name: vm-manager
      file: templates/vm-manager.yml
    - name: vm-infrastructure
      file: templates/vm-infrastructure.yml
    - name: vm-applications
      file: templates/vm-applications.yml

  mountpaths:
    - name: config
      path: /etc
      volume: replicated
    - name: docs
      path: /var/docs
      volume: replicated
    - name: data
      path: /var/data
      volume: local
    - name: logs
      path: /var/logs
      volume: local
    - name: serve
      path: /var/serve
      volume: distributed

  resources:
    - name: vm-manager
      tags: [ vm, management ]
      properties:
        template: vm-manager
        provider: kamatera
        count: 1
    - name: vm-infrastructure
      tags: [ vm, infrastructure ]
      properties:
        template: vm-infrastructure
        provider: kamatera
        count: 2
    - name: vm-applications
      tags: [ vm, applications ]
      properties:
        template: vm-applications
        provider: kamatera
        count: 2
