name: Get Bitwarden
description: Install and authenticate Bitwarden Secrets Manager CLI

inputs:
  bitwarden_token:
    description: Bitwarden session token
    required: true

runs:
  using: composite
  steps:
    - name: Install Bitwarden Secrets Manager CLI
      shell: bash
      run: |
        curl -LO "https://github.com/bitwarden/sdk-sm/releases/download/bws-v1.0.0/bws-x86_64-unknown-linux-gnu-1.0.0.zip"
        unzip bws-x86_64-unknown-linux-gnu-1.0.0.zip
        sudo mv bws /usr/local/bin/
        bws --version  # should output: 1.0.0

    - name: Authenticate with Bitwarden Secrets Manager
      shell: bash
      env:
        BWS_ACCESS_TOKEN: ${{ inputs.bitwarden_token }}
      run: |
        export BWS_ACCESS_TOKEN=$BWS_ACCESS_TOKEN
        bws config profile default --access-token "$BWS_ACCESS_TOKEN"
