name: Get Bitwarden
description: Installs Bitwarden CLI and authenticates using BITWARDEN_TOKEN

inputs:
  bitwarden_token:
    description: Bitwarden session token
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Bitwarden Secrets Manager CLI
      run: |
        curl -L "https://vault.bitwarden.com/download/?app=secrets-manager-cli&platform=linux" -o bws.zip
        unzip bws.zip -d /usr/local/bin
        chmod +x /usr/local/bin/bws
        bws --version

    - name: Authenticate with Bitwarden Secrets Manager
      run: |
        export BWS_ACCESS_TOKEN=${{ inputs.bitwarden_token }}
