# This workflow deploys all services to the shared environment
name: Deploy All Services

on:
  workflow_dispatch:

jobs:
  deploy_platform:
    name: Deploy Services
    uses: ./.github/workflows/_service.yml
    with:
      workspace: platform
      environment: infra
      services: "*"
    secrets:
      BITWARDEN_TOKEN: ${{ secrets.BITWARDEN_TOKEN }}
