# This workflow deploys services
name: Services - Infrastructure

on:
  workflow_dispatch:

jobs:
  deploy_platform:
    name: Deploy Services
    uses: ./.github/workflows/_service.yml
    with:
      workspace: platform
      environment: infra
      services: "traefik"
    secrets:
      BITWARDEN_TOKEN: ${{ secrets.BITWARDEN_TOKEN }}
